# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title : Aiden Nibali
email: dismal.denizen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Aiden and this is my little corner of the Internet. I'm a
  programmer and electronic engineer from Victoria, Australia with a passion
  for open source software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aiden.nibali.org" # the base hostname & protocol for your site
linkedin_username: anibali
github_username:  anibali

# Build settings
markdown: kramdown
